import type { BusinessConfig, TimeWindow, WeeklyHours } from './types';

const closed: readonly TimeWindow[] = [];
const window = (start: string, end: string): readonly TimeWindow[] => [{ start, end }];

const week = (weekday: readonly TimeWindow[], saturday = weekday, sunday = closed): WeeklyHours => ({
  0: sunday,
  1: weekday,
  2: weekday,
  3: weekday,
  4: weekday,
  5: weekday,
  6: saturday,
});

const standardPolicy = {
  slotStepMinutes: 30,
  minimumNoticeMinutes: 120,
  bookingHorizonDays: 90,
  cancellationNoticeMinutes: 24 * 60,
  requiresApproval: false,
  depositsEnabled: false,
  depositPercent: 0,
} as const;

export const businesses = [
  {
    id: 'barber-demo',
    preset: 'barber',
    name: 'Northline Barber',
    tagline: 'Appointments with the right barber, not just an open chair.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('09:00', '18:00'), window('10:00', '16:00')),
    policy: { ...standardPolicy, slotStepMinutes: 15, minimumNoticeMinutes: 60 },
    services: [
      {
        id: 'haircut',
        name: 'Haircut',
        description: 'Consultation, cut and finish.',
        mode: 'appointment',
        durationMinutes: 45,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 45000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business'],
      },
      {
        id: 'cut-beard',
        name: 'Cut + beard',
        description: 'Full haircut and beard shaping.',
        mode: 'appointment',
        durationMinutes: 75,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 65000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business'],
      },
    ],
    resources: [
      { id: 'maya', name: 'Maya', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['haircut', 'cut-beard'] },
      { id: 'jonas', name: 'Jonas', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['haircut'] },
    ],
  },
  {
    id: 'clinic-demo',
    preset: 'clinic',
    name: 'Harbor Clinic',
    tagline: 'Controlled appointment capacity with approval-ready workflows.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('08:00', '17:00'), closed),
    policy: { ...standardPolicy, minimumNoticeMinutes: 12 * 60, requiresApproval: true },
    services: [
      {
        id: 'consultation',
        name: 'General consultation',
        description: 'Initial or follow-up consultation.',
        mode: 'appointment',
        durationMinutes: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 80000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business', 'virtual'],
      },
      {
        id: 'vaccination',
        name: 'Vaccination',
        description: 'Short clinical appointment with observation buffer.',
        mode: 'appointment',
        durationMinutes: 20,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 35000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business'],
      },
    ],
    resources: [
      { id: 'dr-lind', name: 'Dr. Lind', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['consultation'] },
      { id: 'nurse-2', name: 'Nurse station 2', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['vaccination'] },
    ],
  },
  {
    id: 'restaurant-demo',
    preset: 'restaurant',
    name: 'Common Table',
    tagline: 'Party-size aware reservations across real table inventory.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('17:00', '22:30'), window('12:00', '22:30'), window('12:00', '21:00')),
    policy: { ...standardPolicy, slotStepMinutes: 30, minimumNoticeMinutes: 30 },
    services: [
      {
        id: 'dinner',
        name: 'Table reservation',
        description: 'Dinner seating with a two-hour table allocation.',
        mode: 'capacity',
        durationMinutes: 120,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 0,
        maxPartySize: 8,
        resourceKinds: ['table'],
        deliveryModes: ['business'],
      },
    ],
    resources: [
      { id: 'table-2a', name: 'Table 2A', kind: 'table', sharing: 'exclusive', capacity: 2, serviceIds: ['dinner'] },
      { id: 'table-4a', name: 'Table 4A', kind: 'table', sharing: 'exclusive', capacity: 4, serviceIds: ['dinner'] },
      { id: 'table-4b', name: 'Table 4B', kind: 'table', sharing: 'exclusive', capacity: 4, serviceIds: ['dinner'] },
      { id: 'table-8', name: 'Communal 8', kind: 'table', sharing: 'exclusive', capacity: 8, serviceIds: ['dinner'] },
    ],
  },
  {
    id: 'hotel-demo',
    preset: 'hotel',
    name: 'Still House Hotel',
    tagline: 'Date-range reservations against room inventory.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('00:00', '23:59')),
    policy: { ...standardPolicy, slotStepMinutes: 1440, minimumNoticeMinutes: 180, bookingHorizonDays: 365, depositsEnabled: true, depositPercent: 20 },
    services: [
      {
        id: 'standard-room',
        name: 'Standard room',
        description: 'One to four nights in a standard double room.',
        mode: 'stay',
        durationMinutes: 24 * 60,
        bufferBeforeMinutes: 120,
        bufferAfterMinutes: 180,
        priceCents: 149500,
        maxPartySize: 2,
        resourceKinds: ['room'],
        deliveryModes: ['business'],
        startTimes: ['15:00'],
      },
    ],
    resources: [
      { id: 'room-301', name: 'Room 301', kind: 'room', sharing: 'exclusive', capacity: 2, serviceIds: ['standard-room'] },
      { id: 'room-302', name: 'Room 302', kind: 'room', sharing: 'exclusive', capacity: 2, serviceIds: ['standard-room'] },
      { id: 'room-303', name: 'Room 303', kind: 'room', sharing: 'exclusive', capacity: 2, serviceIds: ['standard-room'] },
    ],
  },
  {
    id: 'studio-demo',
    preset: 'studio',
    name: 'Form Studio',
    tagline: 'Pooled class capacity without pretending every seat is a separate resource.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('06:00', '20:00'), window('08:00', '14:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 30 },
    services: [
      {
        id: 'mobility-class',
        name: 'Mobility class',
        description: 'Small-group guided mobility session.',
        mode: 'capacity',
        durationMinutes: 60,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 18000,
        maxPartySize: 4,
        resourceKinds: ['space'],
        deliveryModes: ['business'],
        startTimes: ['07:00', '12:00', '18:00'],
      },
    ],
    resources: [
      { id: 'studio-a', name: 'Studio A', kind: 'space', sharing: 'pooled', capacity: 12, serviceIds: ['mobility-class'] },
    ],
  },
  {
    id: 'interior-demo',
    preset: 'interior-design',
    name: 'Atelier North',
    tagline: 'Design consultations that can happen in-studio, online, or in the client space.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('09:00', '18:00'), window('10:00', '14:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 4 * 60 },
    services: [
      {
        id: 'design-consultation',
        name: 'Interior design consultation',
        description: 'Goals, layout, materials and next-step recommendations.',
        mode: 'appointment',
        durationMinutes: 75,
        bufferBeforeMinutes: 15,
        bufferAfterMinutes: 15,
        priceCents: 120000,
        maxPartySize: 2,
        resourceKinds: ['person'],
        deliveryModes: ['business', 'customer', 'virtual'],
        intakeFields: [
          { id: 'project-type', label: 'Project type', type: 'select', required: true, options: ['Single room', 'Whole home', 'Office / commercial', 'Other'] },
          { id: 'project-location', label: 'Project location', type: 'text', required: false, placeholder: 'City or address for on-site consultations' },
          { id: 'design-goals', label: 'What would you like help with?', type: 'textarea', required: true, placeholder: 'Layout, lighting, furniture, materials, renovation scope…' },
        ],
      },
      {
        id: 'space-planning',
        name: 'Space planning session',
        description: 'Focused room layout and circulation planning.',
        mode: 'appointment',
        durationMinutes: 120,
        bufferBeforeMinutes: 15,
        bufferAfterMinutes: 15,
        priceCents: 220000,
        maxPartySize: 2,
        resourceKinds: ['person'],
        deliveryModes: ['customer', 'virtual'],
      },
    ],
    resources: [
      { id: 'designer-elias', name: 'Elias', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['design-consultation', 'space-planning'] },
      { id: 'designer-liv', name: 'Liv', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['design-consultation'] },
    ],
  },
  {
    id: 'audio-demo',
    preset: 'audio-consulting',
    name: 'Signal Room Audio',
    tagline: 'System design, room acoustics and installation planning by appointment.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('10:00', '18:00'), window('10:00', '15:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 4 * 60 },
    services: [
      {
        id: 'audio-consultation',
        name: 'Audio system consultation',
        description: 'Plan speakers, electronics, sources and system architecture.',
        mode: 'appointment',
        durationMinutes: 60,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 95000,
        maxPartySize: 2,
        resourceKinds: ['person'],
        deliveryModes: ['business', 'customer', 'virtual'],
        intakeFields: [
          { id: 'system-goal', label: 'Primary goal', type: 'select', required: true, options: ['Stereo music', 'Home cinema', 'Whole-home audio', 'Studio / production', 'Other'] },
          { id: 'current-system', label: 'Current equipment', type: 'textarea', required: false, placeholder: 'Speakers, amplifier, sources, room size or existing wiring' },
          { id: 'budget', label: 'Approximate budget', type: 'select', required: false, options: ['Under 10,000', '10,000–25,000', '25,000–75,000', '75,000+', 'Not decided'] },
        ],
      },
      {
        id: 'room-calibration',
        name: 'On-site room calibration',
        description: 'Measurement-led placement, setup and calibration visit.',
        mode: 'appointment',
        durationMinutes: 120,
        bufferBeforeMinutes: 30,
        bufferAfterMinutes: 30,
        priceCents: 180000,
        maxPartySize: 2,
        resourceKinds: ['person'],
        deliveryModes: ['customer'],
        intakeFields: [
          { id: 'service-address', label: 'Service address', type: 'text', required: true },
          { id: 'system-details', label: 'System and room details', type: 'textarea', required: true },
        ],
      },
    ],
    resources: [
      { id: 'audio-nora', name: 'Nora', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['audio-consultation', 'room-calibration'] },
    ],
  },
  {
    id: 'legal-demo',
    preset: 'legal',
    name: 'North Counsel',
    tagline: 'Confidential consultations with intake and approval before the meeting.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('08:30', '17:30'), closed),
    policy: { ...standardPolicy, minimumNoticeMinutes: 12 * 60, requiresApproval: true },
    services: [
      {
        id: 'legal-consultation',
        name: 'Initial legal consultation',
        description: 'A first discussion to understand the matter and possible next steps.',
        mode: 'appointment',
        durationMinutes: 45,
        bufferBeforeMinutes: 10,
        bufferAfterMinutes: 15,
        priceCents: 150000,
        maxPartySize: 2,
        resourceKinds: ['person'],
        deliveryModes: ['business', 'virtual'],
        intakeFields: [
          { id: 'matter-type', label: 'Matter type', type: 'select', required: true, options: ['Contract', 'Employment', 'Family', 'Property', 'Business', 'Other'] },
          { id: 'matter-summary', label: 'Brief summary', type: 'textarea', required: true, placeholder: 'Avoid highly sensitive details in this demo.' },
        ],
      },
    ],
    resources: [
      { id: 'counsel-freja', name: 'Freja', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['legal-consultation'] },
      { id: 'counsel-otto', name: 'Otto', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['legal-consultation'] },
    ],
  },
  {
    id: 'tutoring-demo',
    preset: 'tutoring',
    name: 'Study Hall',
    tagline: 'One-to-one tutoring with subject matching and flexible delivery.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('14:00', '20:00'), window('09:00', '16:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 120 },
    services: [
      {
        id: 'tutoring-session',
        name: 'Private tutoring',
        description: 'Focused one-to-one support for school or university subjects.',
        mode: 'appointment',
        durationMinutes: 60,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 55000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business', 'virtual'],
        intakeFields: [
          { id: 'subject', label: 'Subject', type: 'select', required: true, options: ['Mathematics', 'Science', 'Languages', 'Programming', 'Other'] },
          { id: 'learning-goal', label: 'Current goal', type: 'text', required: true, placeholder: 'Exam preparation, homework, fundamentals…' },
        ],
      },
    ],
    resources: [
      { id: 'tutor-elsa', name: 'Elsa', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['tutoring-session'] },
      { id: 'tutor-noah', name: 'Noah', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['tutoring-session'] },
    ],
  },
  {
    id: 'home-service-demo',
    preset: 'home-service',
    name: 'Fixline Home Services',
    tagline: 'Field-service estimates with travel buffers and address intake.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('08:00', '17:00'), closed),
    policy: { ...standardPolicy, minimumNoticeMinutes: 24 * 60, requiresApproval: true },
    services: [
      {
        id: 'home-estimate',
        name: 'Home service assessment',
        description: 'On-site assessment before repair, installation or maintenance work.',
        mode: 'appointment',
        durationMinutes: 60,
        bufferBeforeMinutes: 30,
        bufferAfterMinutes: 30,
        priceCents: 65000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['customer'],
        intakeFields: [
          { id: 'service-address', label: 'Service address', type: 'text', required: true },
          { id: 'issue', label: 'What needs attention?', type: 'textarea', required: true, placeholder: 'Describe the issue, appliance, fixture or installation.' },
        ],
      },
    ],
    resources: [
      { id: 'tech-ida', name: 'Ida', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['home-estimate'] },
      { id: 'tech-leo', name: 'Leo', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['home-estimate'] },
    ],
  },
  {
    id: 'photography-demo',
    preset: 'photography',
    name: 'Frame Studio',
    tagline: 'Portrait and location sessions with prep and turnaround context captured up front.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('09:00', '18:00'), window('10:00', '16:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 24 * 60, depositsEnabled: true, depositPercent: 25 },
    services: [
      {
        id: 'portrait-session',
        name: 'Portrait session',
        description: 'A guided portrait session in studio or on location.',
        mode: 'appointment',
        durationMinutes: 90,
        bufferBeforeMinutes: 20,
        bufferAfterMinutes: 30,
        priceCents: 180000,
        maxPartySize: 6,
        resourceKinds: ['person'],
        deliveryModes: ['business', 'customer'],
        intakeFields: [
          { id: 'session-type', label: 'Session type', type: 'select', required: true, options: ['Individual', 'Couple', 'Family', 'Team / brand'] },
          { id: 'location-notes', label: 'Location or concept', type: 'textarea', required: false },
        ],
      },
    ],
    resources: [
      { id: 'photographer-maja', name: 'Maja', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['portrait-session'] },
    ],
  },
  {
    id: 'beauty-demo',
    preset: 'beauty',
    name: 'Still Beauty',
    tagline: 'Personal-care appointments with provider availability and service-specific intake.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('09:00', '19:00'), window('09:00', '16:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 60 },
    services: [
      {
        id: 'facial',
        name: 'Facial treatment',
        description: 'Consultation and tailored treatment.',
        mode: 'appointment',
        durationMinutes: 60,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 85000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business'],
        intakeFields: [
          { id: 'skin-notes', label: 'Skin sensitivities or goals', type: 'textarea', required: false },
        ],
      },
    ],
    resources: [
      { id: 'beauty-saga', name: 'Saga', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['facial'] },
    ],
  },
  {
    id: 'pet-care-demo',
    preset: 'pet-care',
    name: 'Good Dog Grooming',
    tagline: 'Pet appointments with animal details captured before the slot is confirmed.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('08:00', '17:00'), window('09:00', '14:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 4 * 60 },
    services: [
      {
        id: 'dog-grooming',
        name: 'Dog grooming',
        description: 'Bath, coat care, trim and finishing.',
        mode: 'appointment',
        durationMinutes: 75,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 75000,
        maxPartySize: 1,
        resourceKinds: ['person'],
        deliveryModes: ['business'],
        intakeFields: [
          { id: 'pet-name', label: 'Pet name', type: 'text', required: true },
          { id: 'breed-size', label: 'Breed / size', type: 'text', required: true },
          { id: 'pet-notes', label: 'Coat, behavior or care notes', type: 'textarea', required: false },
        ],
      },
    ],
    resources: [
      { id: 'groomer-linn', name: 'Linn', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['dog-grooming'] },
    ],
  },
] as const satisfies readonly BusinessConfig[];

export const defaultBusiness = businesses[0];
