import type { BusinessConfig, TimeWindow, WeeklyHours } from './types';

const closed: readonly TimeWindow[] = [];
const window = (start: string, end: string): readonly TimeWindow[] => [{ start, end }];

const week = (weekday: readonly TimeWindow[], saturday = weekday, sunday = closed): WeeklyHours => ({
  0: sunday,
  1: weekday,
  2: weekday,
  3: weekday,
  4: weekday,
  5: weekday,
  6: saturday,
});

const standardPolicy = {
  slotStepMinutes: 30,
  minimumNoticeMinutes: 120,
  bookingHorizonDays: 90,
  cancellationNoticeMinutes: 24 * 60,
  requiresApproval: false,
  depositsEnabled: false,
  depositPercent: 0,
} as const;

export const businesses = [
  {
    id: 'barber-demo',
    preset: 'barber',
    name: 'Northline Barber',
    tagline: 'Appointments with the right barber, not just an open chair.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('09:00', '18:00'), window('10:00', '16:00')),
    policy: { ...standardPolicy, slotStepMinutes: 15, minimumNoticeMinutes: 60 },
    services: [
      {
        id: 'haircut',
        name: 'Haircut',
        description: 'Consultation, cut and finish.',
        mode: 'appointment',
        durationMinutes: 45,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 45000,
        maxPartySize: 1,
        resourceKinds: ['person'],
      },
      {
        id: 'cut-beard',
        name: 'Cut + beard',
        description: 'Full haircut and beard shaping.',
        mode: 'appointment',
        durationMinutes: 75,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 65000,
        maxPartySize: 1,
        resourceKinds: ['person'],
      },
    ],
    resources: [
      { id: 'maya', name: 'Maya', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['haircut', 'cut-beard'] },
      { id: 'jonas', name: 'Jonas', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['haircut'] },
    ],
  },
  {
    id: 'clinic-demo',
    preset: 'clinic',
    name: 'Harbor Clinic',
    tagline: 'Controlled appointment capacity with approval-ready workflows.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('08:00', '17:00'), closed),
    policy: { ...standardPolicy, minimumNoticeMinutes: 12 * 60, requiresApproval: true },
    services: [
      {
        id: 'consultation',
        name: 'General consultation',
        description: 'Initial or follow-up consultation.',
        mode: 'appointment',
        durationMinutes: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 10,
        priceCents: 80000,
        maxPartySize: 1,
        resourceKinds: ['person'],
      },
      {
        id: 'vaccination',
        name: 'Vaccination',
        description: 'Short clinical appointment with observation buffer.',
        mode: 'appointment',
        durationMinutes: 20,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 35000,
        maxPartySize: 1,
        resourceKinds: ['person'],
      },
    ],
    resources: [
      { id: 'dr-lind', name: 'Dr. Lind', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['consultation'] },
      { id: 'nurse-2', name: 'Nurse station 2', kind: 'person', sharing: 'exclusive', capacity: 1, serviceIds: ['vaccination'] },
    ],
  },
  {
    id: 'restaurant-demo',
    preset: 'restaurant',
    name: 'Common Table',
    tagline: 'Party-size aware reservations across real table inventory.',
    timezone: 'Europe/Copenhagen',
    currency: 'DKK',
    hours: week(window('17:00', '22:30'), window('12:00', '22:30'), window('12:00', '21:00')),
    policy: { ...standardPolicy, slotStepMinutes: 30, minimumNoticeMinutes: 30 },
    services: [
      {
        id: 'dinner',
        name: 'Table reservation',
        description: 'Dinner seating with a two-hour table allocation.',
        mode: 'capacity',
        durationMinutes: 120,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 0,
        maxPartySize: 8,
        resourceKinds: ['table'],
      },
    ],
    resources: [
      { id: 'table-2a', name: 'Table 2A', kind: 'table', sharing: 'exclusive', capacity: 2, serviceIds: ['dinner'] },
      { id: 'table-4a', name: 'Table 4A', kind: 'table', sharing: 'exclusive', capacity: 4, serviceIds: ['dinner'] },
      { id: 'table-4b', name: 'Table 4B', kind: 'table', sharing: 'exclusive', capacity: 4, serviceIds: ['dinner'] },
      { id: 'table-8', name: 'Communal 8', kind: 'table', sharing: 'exclusive', capacity: 8, serviceIds: ['dinner'] },
    ],
  },
  {
    id: 'hotel-demo',
    preset: 'hotel',
    name: 'Still House Hotel',
    tagline: 'Date-range reservations against room inventory.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('00:00', '23:59')),
    policy: { ...standardPolicy, slotStepMinutes: 1440, minimumNoticeMinutes: 180, bookingHorizonDays: 365, depositsEnabled: true, depositPercent: 20 },
    services: [
      {
        id: 'standard-room',
        name: 'Standard room',
        description: 'One to four nights in a standard double room.',
        mode: 'stay',
        durationMinutes: 24 * 60,
        bufferBeforeMinutes: 120,
        bufferAfterMinutes: 180,
        priceCents: 149500,
        maxPartySize: 2,
        resourceKinds: ['room'],
        startTimes: ['15:00'],
      },
    ],
    resources: [
      { id: 'room-301', name: 'Room 301', kind: 'room', sharing: 'exclusive', capacity: 2, serviceIds: ['standard-room'] },
      { id: 'room-302', name: 'Room 302', kind: 'room', sharing: 'exclusive', capacity: 2, serviceIds: ['standard-room'] },
      { id: 'room-303', name: 'Room 303', kind: 'room', sharing: 'exclusive', capacity: 2, serviceIds: ['standard-room'] },
    ],
  },
  {
    id: 'studio-demo',
    preset: 'studio',
    name: 'Form Studio',
    tagline: 'Pooled class capacity without pretending every seat is a separate resource.',
    timezone: 'Europe/Stockholm',
    currency: 'SEK',
    hours: week(window('06:00', '20:00'), window('08:00', '14:00')),
    policy: { ...standardPolicy, minimumNoticeMinutes: 30 },
    services: [
      {
        id: 'mobility-class',
        name: 'Mobility class',
        description: 'Small-group guided mobility session.',
        mode: 'capacity',
        durationMinutes: 60,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 15,
        priceCents: 18000,
        maxPartySize: 4,
        resourceKinds: ['space'],
        startTimes: ['07:00', '12:00', '18:00'],
      },
    ],
    resources: [
      { id: 'studio-a', name: 'Studio A', kind: 'space', sharing: 'pooled', capacity: 12, serviceIds: ['mobility-class'] },
    ],
  },
] as const satisfies readonly BusinessConfig[];

export const defaultBusiness = businesses[0];
